added tf state backend in azure
ogomezso/tf-cp-cloud-infra-provision pull request #4
Opened 2023-05-19 14:35 UTC by vcosqui

2023-05-19 18:27 UTC, ogomezso requested changes

2023-05-19 18:27 UTC, ogomezso commented on azure/providers.tf
> +      key                  = "terraform.tfstate"
I would extract these setting to tf variables

2023-05-19 18:28 UTC, ogomezso requested changes
I would extract the blob storage settings to tf variables

2023-05-22 07:50 UTC, vcosqui commented
I am afraid it can't be done
apparently init phase does not have access to variables
https://stackoverflow.com/a/65010204

2023-05-22 08:14 UTC, ogomezso commented
> I am afraid it can't be done apparently init phase does not have access to variables https://stackoverflow.com/a/65010204

So perhaps we can put it as plain env variables or even placeholders, I'm trying to avoid having references to specific resources on this repo.

Thanks!

2023-05-23 07:18 UTC, ogomezso approved these changes

2023-05-23 07:18 UTC, ogomezso commented on azure/providers.tf
> +      key                  = "terraform.tfstate"
And perhaps all the backend configuration to a backend.tf file so anyone can easily switch to local backend just avoiding this file

2023-05-23 07:18 UTC, ogomezso approved these changes

2023-05-25 13:18 UTC, merged